### ISSUE TITLE
Forked, what am I doing wrong?

### ISSUE THREAD

**Issue by pr0letariat** [scotte/jekyll-clean#10]
https://github.com/pr0letariat/pr0letariat.github.io

I try to navigate to:

https://pr0letariat.github.io/

But get 404? Not sure what I'm doing wrong.

**Comment by scotte** [comment]
Try updating the _config.yml and replace:

```
baseurl: /jekyll-clean
```

With:

```
baseurl: ''
```

And then push that to gh-pages branch. Hopefully that does it - gh-pages is a bit confusing between personal versus project gh-pages. If that's it I'll clarify the documentation in README and _config.yml.

I might be mis-remembering how to solve this. Please let me know if it works or not, and if not I'll dig a bit more...

Hope that helps!

**Comment by pr0letariat** [comment]
I made the change, unfortunately still 404.

**Comment by scotte** [comment]
OK, I'm sure there's more to it... I think it might have to do with enabling gh-pages in your repository settings? Let me look, sorry I don't have a better memory. :-)

**Comment by scotte** [comment]
Yeah, nothing obvious in settings for this case - what happens when you push to "master" instead?

Sorry - a bit rusty on the subtle details between the default gh-pages jekyll sites versus project pages, and after I get things working I guess I didn't remember how. :-/

**Comment by scotte** [comment]
Ah, yes, master branch - see here https://help.github.com/articles/user-organization-and-project-pages/ :-)

**Comment by pr0letariat** [comment]
Thanks so much! It works!

**Comment by scotte** [comment]
Great! I'm glad that works for you, and sorry I forgot :-/ - I will update the docs to point to the github documentation for the next person (or the next time when I forget).

Hope you find the theme useful - feel free to suggest anything or send pull requests if you have ideas to improve it in a general way. And if not, thanks for at least trying it!
