### ISSUE TITLE
Markdown not converted correctly

### ISSUE THREAD

**Issue by Ri1a** [scotte/jekyll-clean#15]
Hi! I love your jekyll-clean theme!

Now I am encountering to a problem:

I want to add markdown sites, but not as _posts, just as sites. The folder with the .md file is located at /writeups/. But it's not formed correctly...

Here's the webpage:
![markdown_1](https://user-images.githubusercontent.com/32012280/44106043-c8a8b88a-9ff3-11e8-9b85-ec4fde8f1fa1.png)

And here's a code snippet:
```
---
layout: page
title: Writeup's
permalink: /writeups/
---

Writeup's will be published in english! It may appear that the textstyle differs from other texts.

## Hacking Series

<a href="{{ site.baseurl }}/writeups/bwapp">bWAPP - buggy web app</a>

<a href="{{ site.baseurl }}/writeups/hackthebox">HackTheBox</a>
```

I want that it looks like a post, but not that it's a post:D

You have an idea?

**Comment by scotte** [comment]
That's just how Jekyll works - https://jekyllrb.com/docs/posts/#the-posts-folder

If there's another way to do it, I have no idea - you may want to consult the Jekyll documentation, but I don't think this has anything to do with the theme...

**Comment by Ri1a** [comment]
Hmmmm, on my old site this worked. In the folder /writeups/ I had a writeups.md file that worked.

**Comment by scotte** [comment]
Perhaps with a plugin or something like https://jekyllrb.com/docs/collections/ ? Kind of just guessing what it could be. https://jekyllrb.com/docs/templates/#link might be helpful too. Any reason you are using HTML hrefs instead of Markdown links?

You could always push that branch to github (not on master of course) and I can try and see if I can figure it out. Sometimes different versions of jekyll or other dependencies breaks things - but since your previous jekyll site was working OK I'll assume that's not the issue.

Happy to try and help, but I'm not too sure what's going on here. :-/

**Comment by Ri1a** [comment]
OK, I just forked the repo. Here's the [link](https://github.com/Shadow2xx/jekyll-clean). Maybe you have an idea?

**Comment by scotte** [comment]
Ahha, very simple, I think... Looks like you need this file: https://github.com/Shadow2xx/shadow2xx.github.io/blob/master/_layouts/page.html - with that in place in _layouts, it seems to render fine. Give that a try...

The hint was when I ran it locally:
```
Build Warning: Layout 'page' requested in writeups/writeups.md does not exist.
```

**Comment by Ri1a** [comment]
Nice, now it works fine! Thank you so much!

**Comment by Shadow2xx** [comment]
How can I add the markdown to the div class="well"? Now it looks like this:
![markdown_2](https://user-images.githubusercontent.com/32012280/44132116-940f5c78-a057-11e8-97e3-a04c5d2e7852.png)

And when I add the div boxes to the md file, it looks like this:
![markdown_3](https://user-images.githubusercontent.com/32012280/44132146-cf5b6d58-a057-11e8-8ca0-1725e7feb00d.png)

**Comment by Ri1a** [comment]
GitHub Pages supports the markdown="1" attribute to parse markdown inside HTML elements, e.g.

<div class="tip" markdown="1">Have **fun!**</div>

Nice to know:D

**solved**

**Comment by scotte** [comment]
Great, I'm glad you got it all worked out!

**Comment by Shadow2xx** [comment]
You have an idea what this exception could mean?

`YAML Exception reading C:/Users/ricky/Downloads/jekyll-clean-gh-pages/writeups/vulnhub/derpnstink1.md: (<unknown>): mapping values are not allowed in this context at line 3 column 26`

**Comment by scotte** [comment]
Get rid of the ":" at line 3, column 26.

**Comment by Ri1a** [comment]
No error anymore, thanks!

**Comment by Shadow2xx** [comment]
Now I uploaded the site to: https://shadow2xx.github.io/

But it's not converted correctly. Again, any ideas?
