### ISSUE TITLE
I confined comments, but the comments can not show,what's going on?

### ISSUE THREAD

**Issue by junkor** [scotte/jekyll-clean#2]
I configed the _config.yml about comments like this:

```
disqus: 'junkor'
comments: true
```

nothing happened on my pages. any help?

**Comment by igordcard** [comment]
+1

**Comment by igordcard** [comment]
Don't forget to add comments: true to each post's YAML front matter, as explained at https://help.disqus.com/customer/portal/articles/472138-jekyll-installation-instructions.

Scott, maybe you can clarify that requirement in the README.md for folks without much experience with Jekyll or Disqus?

**Comment by scotte** [comment]
Thanks - I agree the documentation for disqus integration needs to be a bit clearer, I'll update it. Thanks for the comments!

**Comment by scotte** [comment]
Sorry, should have done this a LONG LONG time ago...
