### ISSUE TITLE
Syntax highlighting won't work until an appropriate file is loaded

### ISSUE THREAD

**Issue by dvergeylen** [scotte/jekyll-clean#5]
Hello,

Thank you for this great Jekyll theme. After some analysis I figured out the output of Pygments was correct although no CSS file was generated to render its output accordingly. This is normal behaviour (see this [link](http://stackoverflow.com/questions/9652490/do-i-need-to-generate-a-css-file-from-pygments-for-my-jekyll-blog-to-enable-col)) but I guess it should be added to the README file for clarity.

I propose a file update below (to be inserted between Disqus and License sections).
I would have done directly a pull request with pleasure but I already forked your repo for my own purposes so I'm afraid I can't do it directly.

Have a nice day!
# Syntax Highlighting

You need to either install or create CSS classes to make the code highlighting work Pygments does visible. You can download your preferred theme [here](https://github.com/richleland/pygments-css) and put it into your css folder.

Before using directly, you first have to remove the `.codehilite` class the repo owner added on every style definition:

``` sh
sed  -i 's/.codehilite /span/' theme.css
```

You then have to call the css file from your _includes/header.html file:

``` html
<link rel="stylesheet" type="text/css" href="/path/to/theme.css">
```

More info can be found on [this Stackoverflow thread](http://stackoverflow.com/questions/9652490/do-i-need-to-generate-a-css-file-from-pygments-for-my-jekyll-blog-to-enable-col).

**Comment by scotte** [comment]
Thank you for reporting this, I really appreciate it!

**Comment by scotte** [comment]
There turned out to be a few different ways to skin this cat - I documented what I think is the simplest path and syntax.
