### ISSUE TITLE
Update Markdown Processor to Kramdown

### ISSUE THREAD

**Issue by dvergeylen** [scotte/jekyll-clean#6]
In _config.yml, kramdown markdown processor should be used instead of redcarpet, as asked by the Github policy ([link](https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/)).

**Comment by dvergeylen** [comment]
I had to update "```" back quotes to "~~~" when defining a code block.

**Comment by scotte** [comment]
Thanks, I planned on doing this very soon, but thanks for the reminder!
